### ISSUE TITLE
will mount hook

### ISSUE THREAD

**Issue by iamjohnlong** [leeoniya/domvm#125] opened 2017-03-31 02:33 UTC
Should `willMount` be called before `render`? 

https://jsfiddle.net/iamjohnlong/73eu25bz/

**Comment by lawrence-dol** [comment] 2017-03-31 04:31
In my opinion, it absolutely should be. I makes no sense to receive the draw notification before the "willMount" of the thing that caused the draw.

**Comment by leeoniya** [comment] 2017-03-31 05:15
that's an interesting observation. let me try to briefly explain how these internals work, and we can figure out what to do.

Currently, `willMount` and `willInsert` (for the root node) are siblings, as are `willUnmount` and `willRemove`. They are meant to be notifiers of insertion and removal from the DOM. As such, they are fired by the final DOM reconciliation pass [1]. This happens waaaay after the new vtree has been generated (by render), diffed vs old vtree, and the recycled dom nodes have been patched.

Think of it this way, how do we know a top-level view [or deep sub-view] will mount? Because we see its vnode in the new vtree (generated by `render()`) but its `vnode.el` has no live parentNode. Without first generating the the new vtree by calling render(), diffing with prior vtree and determining what should be inserted or removed, we have no idea what is "about to" mount or unmount.

This behavior is uniform from top to bottom, including both explicit external `vm.mount()` calls as well as internal implicit `subvm.mount()` calls. While it is possible to handle the external mount as a special case, because we *know* what's gonna happen, this leads to different behavior for implicitly created internal vms - which is bad. If you want a willMount that fires ahead of render, you could:

1. Treat the view initialization itself (when the closure fires) as a hacky and cheap way of signaling that a first render will follow. This of course would not be the case if your code pattern involves creating explicit vms that you don't immediately mount.
2. Within render, test whether it's an "initial" render by testing some cached value in the view closure. by asserting the `vm.node.el`.

I guess i should ask what specifically you're looking to accomplish via this hook and what does the term "willMount" mean to you that is inconsistent with when it fires currently. Is there a use-case where invoking render before willMount prevents a certain pattern?

I don't see a way to have both uniformity and pre-render willMount hook, since we need the template before we can mount :)

Thoughts?

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/syncChildren.js#L115

**Comment by leeoniya** [comment] 2017-03-31 05:41
React's componentWillMount does fire before its render [1].

Thinking about it more, this may be possible to accomplish, but it will cost some perf.

When a vtree is created by a parent component, after the findDonor pass vs the old vtree, any child view placeholder for which no donor was located can be assumed to willMount, given that the the parent view is already mounted, which is currently not tracked. The large perf impact though will come as a result of needing to have a matching willUnmount. There is no early "what should be removed" pass over the old vtree (there was in domvm v1). All the insertions and removals are handled by a single pass at the very end in syncChildren. Adding this extra pass for the pleasure of pre-render mount hooks will need some solid justification.

[1] https://facebook.github.io/react/docs/react-component.html#componentwillmount

**Comment by iamjohnlong** [comment] 2017-03-31 13:52
Whats the use case for having willMount then? I was going to use it to set up some initial state on the vm model, but I can just do that in the closure. I was expecting willMount to behave like mithril's oninit.

**Comment by leeoniya** [comment] 2017-03-31 14:33
> Whats the use case for having willMount then?

that's a good question. all vm hooks are available externally to the vm via vm.hook(), in contrast to vnode hooks that can only be attached from render(). i can't give you a specific use-case when they would be useful, but external consumers can manip the vm's detached dom and vtree just prior to insertion.

> I was expecting willMount to behave like mithril's oninit.

from mithril docs it sounds like oninit does exactly what the vm's contructor/view closure does. it might be a good idea to add oninit that's also externally accessible and runs the same as the view closure does. the question is should it run before or after the closure?

**Comment by lawrence-dol** [comment] 2017-03-31 17:29
> render() is not a draw notification, it's a template generator.

Because of my background with graphic's painting systems, I continue to think of "rendering" as the physical act of painting to a graphics surface. This is a mistaken idea on my part. Having read your explanation of the terms, current behavior is perfectly sensible.

> have a will/did pair that runs before/after

I am not seeing the benefit of init hooks. But if they come at little or no cost, it probably makes sense in allowing things to happen which are disjoint from a component's initialization code. In other words, things that are the concern of the parent.

**Comment by leeoniya** [comment] 2017-03-31 17:34
> Because of my background with graphic's painting systems, I continue to think of "rendering" as the physical act of painting to a graphics surface.

```
"There are only two hard things in Computer Science: cache invalidation and naming things."
-- Phil Karlton
```

> But if they come at little or no cost, it probably makes sense in allowing things to happen which are disjoint from a component's initialization code. In other words, things that are the concern of the parent.

Yeah, this would be the main use. The cost should be negligible. While it's possible to get the same thing mostly done in userspace, having predefined hooks would make things cleaner.

**Comment by leeoniya** [comment] 2017-03-31 17:45
opened #126 for this enhancement (not convinced it's really needed yet). closing this, since `willMount` hooks are working as designed.

**Closed by leeoniya** 2017-03-31 17:45 UTC
