### ISSUE TITLE
an isomorphic example domvm application?

### ISSUE THREAD

**Issue by grumpi** [leeoniya/domvm#67] opened 2016-05-01 09:06 UTC
Hey, I've been silently watching this for a while with interest and today I sat down to try make an isomorphic example app with domvm and express.

Context: I'm not an experienced JavaScript developer at all. I do have some experience hacking JavaScript with jQuery, but that's it. I have very little clue about NodeJS, and I don't know any JS frameworks well (I tried mithril for a little and liked the general direction), so I might just be missing something obvious here or I might be trying to do things totally the wrong way. :)

Use Case:
- graceful degradation in the absence of JavaScript.
- fast initial page load on mobile devices on all routes for an application that makes API requests. (On initial page load, the server should make the API requests (and ideally pull results from its cache) and render html so that the client doesn't have to take all the roundtrips on its slow connection)
- ability to open links in another tab as well as reload the page gracefully

One implication of this use case is that the application has to use the historyAPI instead of hashbang URLs - otherwise I don't know which API requests to make on the server side.

In Mithril I managed to almost get such an example app working (https://github.com/grumpi/mithril-isomorphic-example) - it has one serious flaw: Mithril can't attach to an existing DOM so everything will be rerendered when JavaScript finally runs. This is a problem when there is a form on the site since the user will lose all the data they entered before JavaScript ran. As far as I understand, domvm can attach to an existing DOM gracefully.

What I tried to do:
1) make a simple domvm application with a router (this seemed straightforward and works).
2) render all the routes of the application server-side, based on the request path. Basically, I tried to run vm.html(vm.node) after using the router on the server side. That doesn't work because the router is for browser use only.

My current ideas:
1) I use a modified router implementation that can run both on the server and the client, Then, there's only one Express-route in the application that handles all the domvm-routes and I have maximal code sharing between server/client.
2) I make one "routes" declaration format that is transformed to Express-routes and to domvm-routes. This would let me avoid modifying the router but it seems a little more involved.
3) I search for a different reasonable and minimal router implementation that works both in the browser and in nodejs and try to use that instead.

I'm kind of torn between wanting to make a rich, interactive, offline-enabled client side experience and not breaking the web. Essentially, if it comes down to it, not breaking the web for people who are just browsing is more important to me. (I'm fine with people who want to interact being required to use a compatible JavaScript-enabled browser.) Yet, I think I'm really close to being able to have both with domvm. Has anyone tried to do or done something like this with domvm before?

ETA: if the domvm router is supposed to become isomorphic in the future, I wouldn't mind to try help to make it so.

**Comment by grumpi** [comment] 2016-05-01 13:53
Before delving into any of the options I listed, I figured I'd try to see if I can do a quick hack to get server-side routing working without changing the router itself.

Apparently, all that was needed to get things to run on Node was to add `window`, `location` and `history` variables to the global node object. This feels hacky, but it could be worse.

In order to use hrefs generated by the router in my view, I had to define `HTMLElement` as well. In contrast to the previous hack, this one seems more likely to break something.

While the router appears to work, I don't get client-side rehydration of the server-rendered DOM with `attach()`. When I click the links generated by the router, I get page reloads instead of SPA-style navigation. When I call `redraw()`, nothing seems to happen. When I wipe the DOM on the client and have it `mount()` instead, clicking links and redrawing seems to work fine.

I'm probably doing something wrong here.
 
Example code at https://github.com/grumpi/domvm-isomorphic-example

**Comment by leeoniya** [comment] 2016-05-01 14:59
Hey @grumpi 

Thanks for checking domvm out. I have not personally made a fully isomorphic app with domvm yet. I've ensured that SSR (server-side rendering) and client-side hydration works in obvious ways but you're right that the router impl does not currently cater to this. I'm very interested in getting it fully working and don't think it will be difficult to do as it already supports history routing via `useHist: true`. I'm a bit busy today, but will take a look at your code tonight or tomorrow and give you better feedback.

cheers!

**Comment by grumpi** [comment] 2016-05-01 15:52
@leeoniya No need to rush. Hope you're having a nice Sunday.

I think it's great you're making this.

**Comment by leeoniya** [comment] 2016-05-01 21:24
@grumpi thanks!

coincidentally, a lot of router-related stuff in `/r/javascript` today:

https://www.reddit.com/r/javascript/comments/4h8kqq/how_the_best_frontend_router_should_look_like/

https://www.reddit.com/r/javascript/comments/4h99qg/calling_all_routers/

**Comment by leeoniya** [comment] 2016-05-02 05:51
@grumpi take a look at https://github.com/leeoniya/domvm-isomorphic-example.

it's basically working, though for initial nav might be using `replaceState` rather than `pushState`...will need to look into this a bit more but feel free to investigate.

The changes that needed to be made were:

- use `app.view.attach(document.body.firstChild);` since you must attach to the view's root node, not the container it's mounted into. If you want to be more uniform, your view could construct `<body>` and then use `app.view.mount(document.body, true)` and `app.view.attach(document.body.firstChild)`, just make sure your body is has nothing between `</script>` and `</body>` tags. See recent discussion: https://github.com/leeoniya/domvm/issues/56#issuecomment-213210948
- use a local copy of the current domvm 1.x-dev. there was an event-binding regression in 1.1.0 that was fixed a couple days ago: https://github.com/leeoniya/domvm/issues/62
- add `</body>` to response, cause you know...

**Comment by grumpi** [comment] 2016-05-02 09:16
@leeoniya thanks! It's great to see that I was indeed just doing something the wrong way.

* Ok, I see now that attach needs to know the first node rendered by the view and mount just needs a container to dump things into. I just blindly assumed for no particular reason that attach and mount would take the same kind of argument. It does make sense.
* Fair enough, it makes sense to check first with the development branch whenever something odd happens.
* Ah, I hate when I accidentally lose closing tags. One point for rendering the body with a sane language. Though, one argument against rendering the body with domvm is that the `<script>` tag for the application's code will float up into the body in the browser's DOM. Seems like wrapping domvm in its own dedicated div might be more robust / standards compliant.

**Comment by grumpi** [comment] 2016-05-02 19:43
Now I'm approaching mocking an API request.

I suspect the place where to run API requests associated with routes is in the route's respective `onenter()` handler.

I noticed that these handlers are not by default being run on the server side when setting up the router. This makes sense since they might contain all kinds of UI-related initialization magic that should not run on the server.

So I figure that there is a certain part of the `onenter()` handler that needs to run on both client and server - the part that constructs a context for the route.

What I have now is all still very sketchy and not particularly pretty, but I didn't feel like domvm is getting in my way. In fact, it seems straightforward and flexible, just as advertised.

**Comment by leeoniya** [comment] 2016-05-03 02:20
> I noticed that these handlers are not by default being run on the server side when setting up the router.

Right, they're simply callbacks to fire for a matched route.

> Now I'm approaching mocking an API request....

> So I figure that there is a certain part of the onenter() handler that needs to run on both client and server - the part that constructs a context for the route.

I'm not sure what you want the server/client contexts to provide for you in the handlers. You'll have to be more specific here as to what you're trying to accomplish. If you're restricting yourself to features which will work without js enabled, your API is all HTML form GET/POST submissions, form inputs and links for everything else. No JSON, ajax/fetch, etc...right?

**Comment by grumpi** [comment] 2016-05-03 12:41
I'm thinking one reasonable setup for an isomorphic application is to have 1) a backend API server that is responsible for everything related to data/authentication, 2) a nodejs server that handles graceful degradation (by a) rendering and b) providing fallback routes for actions that need to access the API), 3) the user's browser where the fun stuff happens.

Realistically, let's say the API server handles HTTP/Websocket requests and serves JSON while the client running in the browser directly communicates with the API server, just like the nodejs server will. If it doesn't, it's simply a matter of putting a layer on top of it that does.

I'm looking at figuring out an architecture for code-sharing between client and server around domvm that works gracefully in this setup. I'm pretty confident I can hack things together badly, drop datastructures in the first place that makes some sense, and it will probably work more or less, but I think it would be better to do this right.

Please take my ramblings as a call for a sanity check. I'm just thinking out aloud, coming up with something. If you can tell me when what I say or do is bullshit, you're helping a lot. :) I kind of hope for a community to form around domvm that is interested in doing things the "not breaking the web"-way (for the purely selfish reason of getting a glimpse at how others do things). The other frameworks I looked at drop the ball long before there is a chance to get graceful degradation. The best way to get there is probably to talk about isomorphic architectures using domvm.

> I'm not sure what you want the server/client contexts to provide for you in the handlers.

When a route has some data associated with it that is referenced in its view, that should be part of the context for that route. To properly render the view for that route, the code that creates the context (e.g. by doing the API requests and whatever other processing is needed) needs to run before rendering the view - on both client and server, respectively. Maybe there's a better name than "context" I should use for that.

**Comment by leeoniya** [comment] 2016-05-03 15:51
> Maybe there's a better name than "context" I should use for that.

Context is fine, that's what it is.

This all sounds pretty sane. However, I recently had some thoughts about the feasibility of fully isomorphic apps (disregarding the no-js fallback capability) and here is what came out of it. What if your server has state/logic that should not be present on the client but is relevant to rendering? Let's say you have something like:

```js
if (numClients < 5 && day == "tues") {
	// show or don't show some view
}
```

Let's say this statement is contained within some larger `RenderView()` function and you seamlessly wanted to be able to render it on the client rather than returning html. Now you are forced to transmit the full "context" of the server to the client as well as all rendering logic. This was one of those fundamental "uhhh..." that I had no answer for. The implication is that your views' logic (not just the rendered info) cannot rely on any private "context" and the client must have Total Information Awareness (tm).

For simple toy apps this is fine, but for anything non-trivial I'm not sure how this fundamental problem is resolved by other frameworks (if at all). You could in theory somehow "compile" the above logic on the server in real-time to eliminate the conditional and serve only the correct branch to the client, but it becomes very complex very quickly and thus impractical.

**Comment by grumpi** [comment] 2016-05-03 20:51
> What if your server has state/logic that should not be present on the client but is relevant to rendering?

I see this as an issue that is only vaguely related to isomorphic apps. This seems to me to have something to do with the general API-based SPA architecture (or, for that matter, mobile app architecture, since they face the same challenge).

This is a matter of where to make the "cut" between client and API server. You look at your API and make sure it doesn't expose data it shouldn't. (Yes, I have the feeling that many fail at doing this right - and even if it's just by failing to install their MongoDB correctly.)

Any result you need to use in order to make rendering decisions on the client needs to be exposed by the API - however, not necessarily by exposing the actual data that is needed to compute the result. In your example, if your API server may not expose how many clients are currently online and what day it is, you can just expose something less revealing which is still sufficient to let the client know what view to use, instead.

It may seem like, suddenly, presentation logic is being written on the API server that's supposed to only handle data and the data-associated business logic. In some cases, this may even be true. However, doing it this way around seems much more sane than exposing sensitive things that are not the client's business.

Effectively, there seems to be no difference to handing out HTML artifacts generated by the server in terms of "information leaking", if done right. Generating HTML from the data on the server-side is the act of applying a function to the data. Applying a function to the data and then making that available via an API route leaks no more and no less, as long as you pick the right thing to expose.

Does that make sense?

I see the challenge in fully isomorphic, gracefully-degrading, interactive apps in how to make fallback routes for the more complex actions. I think it's fairly safe to say that there exists a class of actions that are not hard to generalize in such a way that you can automatically generate fallback routes on the nodejs server by means of code sharing. Think of anything that can be directly modeled by form submission, like "like"-buttons, newsletter signup, login, logout, etc.

When it gets more complex than that, I'm at a loss how to have things automatically degrade gracefully - other than hand-coding fallback routes and fallback views for complex interactions.

**Comment by leeoniya** [comment] 2016-05-03 21:32
> you can just expose something less revealing which is still sufficient to let the client know what view to use, instead.

yes, this is was also my thought process. you could just return a "showViewX" from the api, but i think this will get very chatty and slow or will need to return some more complex ViewState that can be a single http request. it's hard to say whether such effort to get "mostly isomorphic" is worth it. I think that sticking to the lowest common denominator without stripping a lot of js-only functionality will leave you with nothing more than the ajax-enhanced gmail that launched a decade ago.

> I see the challenge in fully isomorphic, gracefully-degrading, interactive apps in how to make fallback routes for the more complex actions

I like to explore feasibility of designs by starting at some desired result rather than doing a bottom-up design from zero for a theoretically generic abstraction/concern separation. For example, you could consider making a simple contact list with keydown/ajax searching capability, a detail/edit view and a popup phone dialer using domvm. This can be done to flesh out a fully functioning VOIP widget and create the JSON API for it. Stare at your working creation in all its simple glory and then work backwards and see how much of it you can make functional without JS. When you are done with this, see how much you had to give up, how long it took you and what your new codebase looks like.

If you want to fall back to non-js, your HTTP->json translation layer must only communicate via GET/POST, since html forms do not support PUT/DELETE/PATCH. Any needed state/context will need to be shuttled back and forth via form inputs, uris and query strings. Headers/cookies/content-types exist on the server but do not exist in a client router. Etc..

You could probably get a lot of this done with enough time/effort, but again, i dont know whether it's worth supporting the 0.3% of users who somehow expect to use rich web-apps with js disabled. It's one thing if this required no additional cognitive load from a developer, but this is absolutely not the case and it is very far from trivial to develop/structure apps this way.

**Comment by grumpi** [comment] 2016-05-04 14:46
> you could just return a "showViewX" from the api, but i think this will get very chatty and slow or will need to return some more complex ViewState that can be a single http request. it's hard to say whether such effort to get "mostly isomorphic" is worth it.

Ah, but isn't that the normal effort to get a secure and performant single-page-application (or, for that matter, any kind of secure and performant client-server application)?

> I like to explore feasibility of designs by starting at some desired result rather than doing a bottom-up design from zero for a theoretically generic abstraction/concern separation.

Yes to that. While it doesn't hurt to try to mentally order things at a high level before delving into implementation, the practical way to arrive at a useful architecture seems to be to create successively more interesting example implementations. Mocking a minimal VOIP application seems a good example, actually.

> If you want to fall back to non-js, your HTTP->json translation layer must only communicate via GET/POST, since html forms do not support PUT/DELETE/PATCH. 

This seems unproblematic since ancient browsers didn't have PUT/DELETE/PATCH either.

> Any needed state/context will need to be shuttled back and forth via form inputs, uris and query strings. Headers/cookies/content-types exist on the server but do not exist in a client router. Etc..

I think this is where the trouble starts. Basically, one would need to encode any UI state that should be reproducible in the no-js version in the query string of the URI. In a component-based design that means that every component needs to provide code that encodes its no-js-relevant state. The view context would need to have code for reconstructing the UI state from the query string, so it can be rendered on the server. Sounds possible. Though, there is a maximum length for URIs that can realistically be used: some browsers don't support very large URIs.

> i dont know whether it's worth supporting the 0.3% of users who somehow expect to use rich web-apps with js disabled

I think you're probably right (even though not everyone is voluntarily without proper js support and, in practice, the number is a little higher since we have to count everyone with an incompatible browser, too). Full graceful degradation is more or less a thought experiment to me, at the moment. In practice, I think the sweet spot for graceful degradation on many SPAs is at "making all the interesting content browsable without js under dedicated URLs" - reason being that this spot seems not very expensive to reach and doesn't impose any ongoing cost on the SPA client development.

What we've brought up are these two concerns for a client-server architecture:

1. avoiding unintentional disclosure of information (this **must** be solved at the backend side by not exposing anything that shouldn't be exposed)
2. performance loss due to subsequent roundtrips when there are lots of client-server-calls (this **should** be solved at the backend side by making an interface that minimizes the number of required roundtrips)

I was wrong saying that the SPA client must always communicate with the API server directly. That would mean we have to put presentation-related logic into the API if we wanted to resolve both these concerns. Now I think the reasonable place for that to live is in the SPA server.

In my personal case, I think that a great deal of confusion comes from having been exposed to convoluted, tightly-integrated backend implementations that mix presentation-logic and data-logic. The frameworks themselves aren't really the problem, it's the convoluted way they're used.

The backend is:

* the API server (written in any language/backend framework, possibly facing the public internet in order to allow connections directly between API server and SPA client for those cases where that makes sense)
* the SPA server (nodejs, facing the public internet under TLS)

The frontend is:
* the SPA client (running in the user's browser)

Responsibilities:

* API server: serves a public API secured by authorization, authentication under TLS. Must not leak information!
* SPA server: serves the code of the SPA client to the user's browser. Partially isomorphic: Renders HTML pages for 1) clients that have no JS and 2) mobile devices on horribly slow connections so they can view page content. Computes view state for AJAX-heavy view contexts by making requests to the API server and computing things on behalf of the SPA client in order to reduce roundtrips.

I don't know if there's a framework that forces/assumes an architecture like this. From what I glimpsed reading docs of frontend js frameworks, they usually just deal with the SPA client side and leave it at that. It would surely be interesting to know what the "full stack js frameworks" do to mitigate the risks of accidentally leaking information or to optimize performance for views with AJAX-heavy context setup.

**Comment by leeoniya** [comment] 2016-05-05 14:49
https://www.reddit.com/r/javascript/comments/4htswa/isomorphic_react_and_seo_the_benefits_of_a_single/

**Comment by lawrence-dol** [comment] 2016-05-05 20:05
> Full graceful degradation is more or less a thought experiment to me, at the moment. In practice, I think the sweet spot for graceful degradation on many SPAs is at "making all the interesting content browsable without js under dedicated URLs"

I think at some point you have to decide whether you're delivering an app or a web page; if the former I think JavaScript is a reasonable minimal requirement and a simple notice saying "This application requires JavaScript to function" is fine. If you are delivering a web page, then JavaScript use should be minimal with the content fully reachable without it.

> Renders HTML pages for [...] 2) mobile devices on horribly slow connections so they can view page content.

The irony being that delivering just the data content instead of full HTML is likely to be far more performant if the gating consideration is *link* speed.

A well designed API will be able to cater to different client's needs and limitations in layers. It's fairly simple to build and maintain a course-grained mobile app API on top of a fine-grained, more flexible one. Especially if one allows a standardized way of the client telling the server what data it's interested in (from the set of data the API is permitted to send that user, of course), as a response-size-limiting capability.

**Comment by grumpi** [comment] 2016-05-06 09:46
> The irony being that delivering just the data content instead of full HTML is likely to be far more performant if the gating consideration is link speed.

Right, as soon as all the scripts have loaded, it's much faster. From what I understand, the bottleneck is both latency and bandwith. So both number of roundtrips and application size should be minimal in order to load things fast. The thing is that, if it's a pretty large application, having to wait something like 20 seconds (~ a 125kb app on GPRS at 50kbps, if I'm calculating correctly) to load all the necessary scripts before the page can render is painful and quite off-putting to prospective users.

Showing a page that lets them see content and the information that there's still something loading can be the difference between the prospective user thinking "this is total crap and doesn't work, I'm out" and "ok, this looks interesting, I'll wait until it loaded" (or "I'll look at this again when I got a better connection again"). It's about making a good first impression. Sure, we can always put a generic "It's loading"-page instead of a blank page, but that still creates a mismatch between what the user sees and what they expected following the link to the content.

I suppose one can achieve "fast enough (but still slower than dumping HTML from the server, thanks to the additional round-trip)" "time to first content" by having different builds of the SPA. Have a "non-registered user"-build that contains only content-rendering views and not the interactive parts and one "registered user"-build that makes up the whole application. In the latter case, application size is not a concern because these users will have the scripts cached (or, if they don't they at least already know what they're waiting for). Though, splitting the app in this way looks more complicated to me than just generally rendering HTML on the server.

**Closed** 2017-01-10 23:17 UTC
Labels: discuss
