### ISSUE TITLE
Wiki for API

### ISSUE THREAD

**Issue by 0419** [leeoniya/domvm#112] opened 2017-01-27 04:24 UTC
Trying to learn the new api, and migrate old admin code from 1.x branch to new api. A reference documentation as WIKI for api would be really helpful. It can be just one line description and sample usage, not a lot.

e.g. 

I am unable to find what API i have to use to show navbar in layout
 
```
function LayoutView(vm, layout) {
	layout.nav = new Navbar({title: 'Admin'});

	return function() {
		return el("div", [
			layout.nav.view,            /// ??????
			el(".container-fluid")
		]);
	}
}
```

**Comment by leeoniya** [comment] 2017-01-27 05:42
yeah, sorry. v2 docs are non-existent. it's basically "read the demos"

all vnodes now have factories:

```js
var el = domvm.defineElement,
    tx = domvm.defineText,
    cm = domvm.defineComment,
    vw = domvm.defineView,
    iv = domvm.injectView,
    ie = domvm.injectElement;
```

you'd want to use `vw` or `iv` depending on if you're injecting an existing vm or simply declaring a view.

`defineText` is not strictly necessary, since the pre-processor will convert numbers/strings into text nodes for you [1].

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/preProc.js#L48

**Comment by iamjohnlong** [comment] 2017-02-03 17:27
How do the views update/redraw in https://github.com/leeoniya/domvm/blob/2.x-dev/demos/streams.html without calling `vm.redraw` ?

**Comment by leeoniya** [comment] 2017-02-03 18:15
after any redraw, if preprocessor detects a stream-esque value returned in the new template, it automatically chains a single-fire redraw onto the stream. put another way, it creates a dependent stream that will only invoke once and automatically unsubscribe.

this means that the dependent streams are destroyed and re-created on every redraw. this wouldn't fare well for any synthetic benchmarks, but it works quite fast in real life.

**Comment by iamjohnlong** [comment] 2017-02-03 18:25
That makes sense. Is there a way to disable it? How does `diff` work and when/why should it be used?

**Comment by leeoniya** [comment] 2017-02-03 18:37
> That makes sense. Is there a way to disable it?

1. You can use (or generate) a build [0] that doesn't include `streamFlyd`.
2. You can just use the stream's values rather than the actual streams into your templates.
3. For any builds that have the capability of stream handling (mini+) [4], you can call `domvm.streamCfg` to override the `is` to always return `false` so nothing is ever detected as a stream.

The last option seems moot, since including a raw stream object directly ina  template will stringify to `[Object object]` or whatever if `toString` is not explicitly implemented in your stream flavor.

`diff` is explained here [1], you can see it used in [2] (commented/optimized impls) and [3].

[0] https://github.com/leeoniya/domvm/blob/2.x-dev/dist/README.md
[1] https://github.com/leeoniya/domvm/issues/111#issuecomment-275710310
[2] https://github.com/leeoniya/domvm/blob/2.x-dev/demos/bench/dbmonster/app.js
[3] https://github.com/leeoniya/domvm/blob/2.x-dev/demos/immutable.html
[4] https://github.com/leeoniya/domvm/blob/2.x-dev/src/builds/mini.js#L8

**Comment by leeoniya** [comment] 2017-02-04 00:55
@iamjohnlong out of curiosity, are you secretly working on some docs? ;)

if so, i'll hold off to iterate on your work, otherwise i'll slap some super dense api docs together for the time being. i don't wanna duplicate or throw away any valuable work/contributions.

**Comment by iamjohnlong** [comment] 2017-02-04 15:26
I'm not, but I'd be happy to add to something you cook up, examples and such. I was looking at the immutable demo you have. That turned me on to freezerjs, which I didn't know of. Then I was looking at his React demo with freezer and your immutable demo made more sense of the reasoning behind it. I didn't know `vm.update` existed. 

I haven't built anything with React/Redux, mainly because Redux looks like you have a lot of boilerplate code and could get messy with large apps. Looking at your immutable demo w/ freezer almost seems too easy. Same with React/Freezer [1]. I'm wonder how well it'd scale with large routed apps. I'm going to build the todomvc with domvm/freezer [2] this weekend if I have some free time away from the wife and kids :)

[1] https://medium.com/@arqex/react-the-simple-way-cabdf1f42f12
[2] https://github.com/arqex/freezer-todomvc

**Comment by leeoniya** [comment] 2017-02-04 15:47
the caveat to `vm.update` is that obviously it can never update a model you're closured. so...

```js
function MyView(vm, model) {    // closured model; not affected by vm.update(newModel)
  return function(vm, model) {    // passed model at each redraw; is affected
    return el("div", model.name);
  }
}
```

you can choose which to use on a case-by case basis. this is why `render()`'s sig is identical to the closure's sig. it allows you to make pure components, if needed.

**Comment by iamjohnlong** [comment] 2017-02-10 16:30
@leeoniya https://rawgit.com/iamjohnlong/domvm-freezer-todo/master/index.html

a work in progress, I have a few questions though. I'd like to pass in the freezer `State.trigger` somewhere other then the model. Would the `opts` be a good place for it?

**Comment by leeoniya** [comment] 2017-02-10 16:56
yeah that's the most obvious place to put it if you insist on dep-injecting.

IMO it's easier to designate a global `const STORE = new Freezer({...});` and then use `STORE.trigger()` wherever you need. Passing around all needed dependencies becomes a major pain in the ass for large apps.

**Comment by lawrence-dol** [comment] 2017-02-10 18:25
> Passing around all needed dependencies becomes a major pain

Yes indeed. My approach is to separate reusable modular stuff (at a logical level, not necessarily actually used in another app), from the code which is entirely relevant only to the app. App code utilizes shared state from the encapsulating app context (in my can usually the application closure), which the other modules create their own state and are inject with the things they need to interact with the application, including effort expended in defining a logically coherent and suitably abstract API.

That's been working for me pretty well.

**Comment by iamjohnlong** [comment] 2017-02-10 18:39
I guess for application structure, I'm planning on implementing this with required modules/es6. More or less like https://github.com/arqex/freezer-todomvc

I was following the convention of having a "reactions" file [1] that handles the setting the state

[1] https://github.com/arqex/freezer-todomvc/blob/master/src/todoReactions.js

**Comment by leeoniya** [comment] 2017-02-10 18:51
that implementation seems needlessly complex with a lot of indirection, probably due to React's semantics.

if you're forced to call `State.trigger('todo:clearCompleted');`, then you may as well use `rootVm.redraw()`. the whole point [besides optimized sub-view sCU] is to avoid triggering these things by virtue of a global `update` event emitted by a central store.

i would recommend working off of @yosbelms 1.x implementation [1] to integrate Freezer and remove the need for explicit `redraw()` calls. You don't really need a pub/sub event system for this at all.

[1] https://github.com/leeoniya/domvm/tree/1.x-dev/demos/TodoMVC

**Comment by iamjohnlong** [comment] 2017-02-10 19:12
shrug, it doesn't seem very complex to me. it's just the approach I took after looking at the freezer todo example already mentioned and https://github.com/mciparelli/inferno-freezer-todomvc

**Comment by leeoniya** [comment] 2017-02-10 19:29
> shrug, it doesn't seem very complex to me.

that's fine, but an implementation with an immutable store that still requires you to explicitly use a pub/sub system is somewhat puzzling to me in terms of benefits. on top of that, any TodoMVC that doesnt contain 10k todo items will benefit little from any form of optimized redraw, given domvm's perf profile.

while creating a distributed, fault-tolerant, microservice AWS-hosted todolist app with SSR rendering might be interesting technically, it's a pretty shitty use case to necessitate 7 levels of indirection and `left-pad` micro-dependencies. enterprise-level complexity should require enterprise-level problems. / $0.02

**Comment by iamjohnlong** [comment] 2017-02-10 19:39
I get your points, it's less about the todo app itself and more thinking about how I would structure a large application using freezer and domvm. If I were writing a todo app for what it's worth I would write it in vanillajs, or the most optimized solution would be a pencil and paper.

**Comment by iamjohnlong** [comment] 2017-02-10 21:42
whether you agree with the implementation I may have found a bug when using keys in `defineView` with `diff` set [1]. The browser freezes when deleting todos and some other odd things.

[1] https://github.com/iamjohnlong/domvm-freezer-todo/blob/master/app.js#L115

**Comment by leeoniya** [comment] 2017-02-10 21:58
can't seem to reproduce. can you provide specific steps and browser you're seeing this in?

**Comment by iamjohnlong** [comment] 2017-02-10 22:04
I uncommented the line https://github.com/iamjohnlong/domvm-freezer-todo/blob/master/app.js#L116

I'm in chrome  56.0.2924.87 (64-bit) on osx

open https://rawgit.com/iamjohnlong/domvm-freezer-todo/master/index.html#/ and hard refresh => add some todos => refresh => delete the first todo => browser freezes

**Comment by leeoniya** [comment] 2017-02-10 22:31
confirmed, thanks. the irony of a browser-freeze bug in a Freezer demo is not lost on me.

so far i've narrowed it down to the reconciliation algo never hitting an exit condition out of this `while` loop [1]. should have a fix hopefully soon.

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/syncChildren.js#L160

**Comment by leeoniya** [comment] 2017-02-10 22:51
@iamjohnlong would you have time to try to get it down to a minimal test case? there's a lot of app to strip down here :/

**Comment by iamjohnlong** [comment] 2017-02-10 22:54
http://pastebin.com/gHMXxFCW that's your immutable.html tweaked

**Comment by leeoniya** [comment] 2017-02-10 23:10
i'm unable to reproduce it in the tweaked immutable.html

**Comment by iamjohnlong** [comment] 2017-02-10 23:35
I'm away from my computer ATM. Be back in a couple hours

**Comment by leeoniya** [comment] 2017-02-11 00:40
i've isolated a test case [1]

it doesnt look like keys cause this, but diff() is definitely involved. the weirdest thing is that the bug only manifests with > 4 sub-views where it causes one error in the reconciler and causes an infinite loop in the reconciler for > 5 sub-views - very odd.

[1] https://gist.github.com/leeoniya/82558c8a3861d715bf451017f0ab746f
[2] https://github.com/leeoniya/domvm/issues/113

**Comment by leeoniya** [comment] 2017-02-11 16:42
issue is fixed.

**Comment by leeoniya** [comment] 2017-02-12 05:07
the discussion no longer corresponds to the title, so closing this.

gonna use some bits from here while working on the docs.

**Closed by leeoniya** 2017-02-12 05:07 UTC
