### ISSUE TITLE
in/out animations

### ISSUE THREAD

**Issue by iamjohnlong** [leeoniya/domvm#32] opened 2016-03-16 15:09 UTC
Do you have any examples of in and out animations using hooks? Such as an image slider that cycles through an array? I'm playing with the hooks for in and out animations and I'm having trouble wrapping my head around it. 

Here is what I have so far. http://jsfiddle.net/75m4k6b0/1/

**Comment by leeoniya** [comment] 2016-03-16 15:38
it looks like it's mostly working.

i think you'd want to have two different classes you *add* in the rAF (`.in-from-left`,`.in-from-right` based on move direction) rather than a single "in" one which you remove. then have the default style to hidden on insertion.

i'll expand more a bit later.

**Comment by leeoniya** [comment] 2016-03-16 15:47
i don't know if you're familiar with WeakMaps [1], but ideally you could store the state of each model outside of the models (if you dont' want to pollute them) and have your render function pull any additional classes/styles from this state object. this way you will not have to do "addClass" and your vm will always be in sync with the dom. otherwise it is very carefully balanced and a redraw that changes the class of the image for some other purpose will blow away any manually added classes.

the lifecycle hooks demo doesn't do us any favors here in showing how to do it properly. i'll have to put something less ad-hoc together in the near future.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

**Comment by iamjohnlong** [comment] 2016-03-16 15:58
Yeah no worries, I know your busy with the core and I don't want sidetrack you. I was more curious if you had something similar cooked up. I'll look into WeakMaps. 

Thanks

**Comment by leeoniya** [comment] 2016-03-16 16:07
let's leave this open, since animations are a bit of a rough spot that needs polish. there needs to be a recommended way to manage retained view state per-node.

i have a demo i'm writing now which is also running into some of these edges for css transitions. which is why there's been a lot of bug fixing in the hooks the last few days.

**Comment by leeoniya** [comment] 2016-03-18 05:00
@iamjohnlong 

Now that lifecycle hooks have some more sanity, I'll do a few slider impls.

The first one is simple and minimal. It doesnt use hooks and doesnt wrap around (it just clamps the indices). Also it loads all the images onto the occluded strip rather than doing any kind of culling.

https://jsfiddle.net/oq72e5x3/

**Comment by iamjohnlong** [comment] 2016-03-18 14:02
@leeoniya awesome, thanks for taking the time.

**Comment by leeoniya** [comment] 2016-03-18 14:13
sure, i'll add some other versions later. of course it doesnt work now cause rawgit

**Comment by iamjohnlong** [comment] 2016-03-18 14:18
Yeah I just copied the lib into a script tag in the html section.

**Comment by leeoniya** [comment] 2016-03-18 14:33
btw, keep me posted if you have to invent hacks to get certain things done with the lib...such as using the recycle hook just to get animations to work.

either it's a lib wart (which i'll want to fix) or it's something that is already possible but lacks proper documentation (which i also want to fix).

These issues are valuable since I will be referencing them to write documentation/tutorials about how to get common problems solved. plus they are good candidates to have working demos for.

**Comment by iamjohnlong** [comment] 2016-03-18 22:37
Here is something I've been playing with https://jsfiddle.net/iamjohnlong/zd4sqjs2/

Let me know what you think. The idea being that you should be able to cycle through images continuously from either direction. Picking from the slides allows you not to load the full set of images incase you have many or they are large and may never be seen.

**Comment by lawrence-dol** [comment] 2016-03-18 23:12
It works well for me in current Firefox, except for a little "flicker" the first time any given image is displayed and then occasionally after that. It looks like the image redraws momentarily at a small or zero size, right at the end of the animation sequence.

**Comment by leeoniya** [comment] 2016-03-19 03:08
@iamjohnlong, @lawrence-dol 

Take a look at the new scoreboard demo [1]. It's an attempt to implement something like @barneycarroll's version [2].

Some important things to note:

- `vm.patch` is used to ensure than both immediate and delayed css is applied and synced into the vtree via the lib. This is critical to making any animation solution robust. Manipulating the DOM directly via classList/className/style should be frowned upon and a last resort; it *will* bite you.
- `vm.patch` requires the old vnode ref and a full new template to replace it with. this is why the player render is pulled out, so it can re-gen the template in various states, including "delayed" to apply the transitions. The plan is to add the ability to `vm.patch` to only patch props, rather than requiring the entire node + children. Likely soon.
- `_ref` and `name` props additionally have the effect of assigning a `_key`, since both should be unique. However, I'm now re-considering `name` as having this effect, since it is easy to have multiple forms with the same-named elements within one view. Originally name was done to avoid form element reuse, but that should no longer be an issue.
- To avoid polluting models and `_ref` needing to be a plain value, it's a bit of a hack to rely on `player.name`. I'd like to have _refs and _keys be mappable to objects, but this would require a 3kb WeakMap shim [3]. Still thinking about it. Also, `_ref` namespacing would be very useful since all players and the new-player form elements all get dumped into the same flat object which necessitates DIY checks when iterating `vm.refs` later.
- Only animating the element order is implemented here. When player are added or removed they pop into place and existing items transition around them, so it's not quite as full as the original, but it's WIP. Feel free to take a stab at getting the rest working.
- If this was a real app, using native HTML5 validation and `required` would take a bit more work to handle the form submit, and avoid some naming collisions that exist in the demo.

I'll come back to the slideshow impl a bit later.

[1] http://leeoniya.github.io/domvm/demos/scoreboard.html
[2] https://jsfiddle.net/barney/3hauLsef/
[3] https://github.com/Benvie/WeakMap

**Comment by iamjohnlong** [comment] 2016-03-19 15:46
Looking good, the only differences I see between this and @barneycarroll 's is the first animation in (which you've stated) and the name's need to be unique (which I'm assuming because the `_ref` needs to be unique? maybe assigning them a GUID as barney does could solve that). This is the first time I've seen the use of `vm.patch`. 

My slide implementation is working without the "flicker" in Chrome Version 49.0.2623.87 (64-bit) and FF 44.0 on my machine OSX 10.11.3 (15D21), but I'm seeing the "flicker" in Safari v9.0.3 (11601.4.4)

I'm wondering if this is an issue with the implementation or the lib?

**Comment by barneycarroll** [comment] 2016-03-19 16:46
@iamjohnlong cool fiddle!

The flicker thing @lawrence-dol noticed is something I've experienced in Chromium a few times when animating images. A couple of years ago I was tasked with creating graphically rich interactive touch displays for a museum exhibition where we limited to very cheap hardware without GPUs, for which this became an unacceptable bug. This is down to the browser's internal black box of wisdom as to when images should be decoded and rendered as part of the paint process. I found you can take control over when this happens by rendering the images via individual canvas elements. This allows you to specify the one point in time when these images are decoded and painted to screen, and incidentally improved performance to the point of 55FPS (up from 20-30) during animation. This would be relatively easy to achieve declaratively with a virtual DOM component instead of an image element.

As regards WeakMaps, I have found maps as a basic structure to be invaluable for any serious work on top of virtual DOM. These are essential to the internal model used by [Exitable](https://github.com/barneycarroll/mithril.exitable.js), for example (the Mithril extension I wrote that enables exit animations in my scoreboard fiddle). It's important to note that performance concerns aside, these are fundamentally the best tool for the task of associating arbitrary objects with others. I use Andrea Giammarchi's [ES6 collections](https://github.com/WebReflection/es6-collections) polyfill for target environments that don't support them natively: it clocks in at >1kb gzipped and offers full API parity. It's worth reading the README for that package for the reasoning as to why it is impossible to polyfill weakness (weakness relies on engine-internal garbage collection to dispose of redundant records) — crucially, any attempt at emulating weakness involves a lot of code and a performance hit when attempting to enforce disposal of redundant records in a way that can never be robust and will always have to hit the main thread to do work which should be done behind the scenes as part of the engine's natural behaviour. In practice, lack of weakness in non-supporting engines is only likely to become a problem if many elements and models are destroyed on a regular basis in an application which is kept alive for very long periods. This kind of problem (application models which continue to grow over long periods) is another one which I had the chance to deal with as a critical concern on that same job with the exhibition displays. We found that forcing the application to refresh upon focus when it had been in continuous session for more than 24 hours solved that problem: if you persist user data to storage and use stateful routing, this technique shouldn't present any problems WRT application state and the trade off of having a user loose a fraction of a second and a potential flicker every 24hrs if they insist on keeping sessions open for long periods is not that bad a trade-off IMO.

**Comment by leeoniya** [comment] 2016-03-19 17:51
@iamjohnlong 

> (which I'm assuming because the _ref needs to be unique? maybe assigning them a GUID as barney does could solve that)

yes (within the vm) and yes since i'm already using WeakMaps, this would be the solution here.

animating in/out should be fairly easy to add actually by patching from use `didInsert` and `willRemove`. currently `willInsert`/`willMount` hooks don't have access to even the detached DOM (they fire before the elems are created), i'm looking into changing this to make them more useful than just notification points.

@barneycarroll 

> As regards WeakMaps, I have found maps as a basic structure to be invaluable for any serious work on top of virtual DOM.

I'm finding this out as well. However, I'm hesitant to make them a hard dependency of the lib since most of their usefulness (if needed) exists in the application layer. That being said, being able to have `_key`, `_ref` as objects is a pretty good case to consider Maps for the core. https://github.com/WebReflection/es6-collections looks interesting.

**Comment by leeoniya** [comment] 2016-03-20 06:26
i've pushed a commit to allow `vm.patch` to accept an object with `{style:.., class..}`.

the scoreboard demo has been updated to use this.

**Comment by iamjohnlong** [comment] 2016-03-21 14:18
Here is the slider with different image sources, I believe that the image app I was using wasn't getting cached properly?

https://jsfiddle.net/iamjohnlong/7svvqpeu/

Let me know if you still see flickering.. Also there needs to be an image loader to prevent loading times from making things wonky. @lawrence-dol @barneycarroll

**Comment by iamjohnlong** [comment] 2016-03-21 19:36
@leeoniya `vm.patch` is super handy with the style object!

**Comment by leeoniya** [comment] 2016-03-21 19:52
yeah it's been on my todo for a while. having to extract the tpl of the full node branch just to patch class/style is not only unecessary overhead but reduces readability by forcing you to break up the structure. i'm glad this addition made the 1.0 cutoff :)

**Comment by leeoniya** [comment] 2016-04-04 01:59
you guys should check out the updated lifecycle hooks demo [1].

it now uses idiomatic `vm.patch()` and new `u.tick()`, which is a huge improvement over the previous ad-hoc `requestAnimationFrame` and `el.classList` manip [2].

i kinda opened up a can of refactoring worms by saying "let's just quickly rewrite the hooks demo using `vm.patch`". it uncovered a bunch of roughness in the expected liveness state of the dom when each hook fired. the final api, however, functions exactly as needed with the upcoming stacked modal widget, so i'm pretty happy about it. think there was also a bit of a perf gain to boot.

[1] https://github.com/leeoniya/domvm/blob/master/demos/lifecycle-hooks.html
[2] https://github.com/leeoniya/domvm/blob/0727bff08aa84103bf6f4697c454cac5af8048d5/demos/lifecycle-hooks.html

**Comment by iamjohnlong** [comment] 2016-04-04 13:31
Looks a lot cleaner with `u.tick()`, I like the sig as well. I'll have to play with it.

**Comment by iamjohnlong** [comment] 2016-04-04 14:31
Should patch clear all attributes on the node? 

https://jsfiddle.net/iamjohnlong/dcfr03y6/

Patching the node clears the id and the custom attr.

**Comment by leeoniya** [comment] 2016-04-04 16:16
it shouldn't. looks like a bug.

btw, `u.tick`, delays a specified number of *frames*, not ms.

```js
domvm.utils.tick([v.redraw], 0);`
```

is the same thing as doing

```js
requestAnimationFrame(function() { v.redraw(); });
```

while

```js
domvm.utils.tick([v.redraw], 10);
```

is the same as

```js
requestAnimationFrame(function() {
    requestAnimationFrame(function() {
        requestAnimationFrame(function() {
            ...
                v.redraw();
});
```

**Comment by iamjohnlong** [comment] 2016-04-04 16:34
@leeoniya Ah I see, noted thanks man.

**Comment by leeoniya** [comment] 2016-04-04 17:05
the patching issue is fixed in the 1.x-dev branch: https://jsfiddle.net/dcfr03y6/4/

**Comment by lawrence-dol** [comment] 2016-04-04 18:31
> u.tick() delays a specified number of frames, not ms.

Curious, but won't this make all animations very dependent on the underlying hardware such that fast hardware will animate too fast and slow hardware too slow, relative to the developer's hardware? Or are animation frames determined at some capped rate? Or are the goal posts sufficiently narrow that the end-result is acceptable at either extreme?

**Comment by iamjohnlong** [comment] 2016-04-04 18:44
that was quick, you're the man.

**Comment by leeoniya** [comment] 2016-04-04 18:57
> Curious, but won't this make all animations very dependent on the underlying hardware such that fast hardware will animate too fast and slow hardware too slow, relative to the developer's hardware?

u.tick's main purpose is to ensure that any patching you need to do is *not* coalesced by the browser and explicitly happens after any prior repaints. so, it's not meant to serve as a timing mechanism but simply a way to ensure something happens in the next frame rather than the current one.

here's a basic thing without domvm: https://jsfiddle.net/a94o7c0y/2/

all `did*` hooks are already ticked by 2 frames relative to the actual insert/patching call (so anywhere between 16ms and 32ms), to ensure that any changes have been repainted to the live DOM. orginally it was 1 frame, but the the cross-browser behavior was non-uniform in slightly more complex cases. if you set `domvm.view.config({useRaf: false})`, then the `did*` hooks will fire immediately, but you will lose liveness guarantees and vm.redraw call coalescing, so it's mostly useful for accurate perf/regression timing.

domvm is not an animation lib and the aim is only to simplify common css transition cases rather than facilitate full-featured, accurate and performant animation chains.

**Comment by lawrence-dol** [comment] 2016-04-06 01:12
By the way, I am really looking forward to playing with integrating CSS animations with DOMVM. This was one area that seems clean where in Mithril it seemed like a nightmare. Thanks for putting polish on this aspect.

Especially because they can really produce a wow-factor in users. And used judiciously they can convey really good feedback to the user as to what's happening.

**Comment by leeoniya** [comment] 2016-04-06 19:14
check out the new stacked modal widget (alpha) [1]. There are some interesting things in it.

First, it uses a small/generic PropCache implementation to store the "current" class/styles per object. This cache is accessible and also used by the render() (so any redraws remain consistent). It also handles merging new styles over the cached ones so repetition can be avoided in the state declarations. ModalStack itself has an exposed api and is responsible for setting up the correct patching hooks from the passed config. Full window blocking is also very easy by just setting the needed overlay css `position: fixed`, rather than `position: absolute`.

Still lots to do, (vertical/horizontal centering, dragging, dismiss on overlay clicks, etc)

There's a good chance that at least some of this will form the basis of a future `effect` module.

[1] http://leeoniya.github.io/domvm/demos/ModalStack/

**Comment by lawrence-dol** [comment] 2016-04-07 00:30
That's very cool, with an impressively small footprint. Well done.

(As an aside, your use of tabs for indenting causes Firefox to completely mess up the code layout in view-source unless you add config value view_source.tab_size=4.)

**Comment by leeoniya** [comment] 2016-04-07 01:02
i've tried switching to spaces, but every time i get going some annoyance makes me tear my hair out. how tab=8 spaces got standardized by w3c or watwg is a mystery to me, just like the content-box default box model.

maybe i'll start adding the css3 `tab-size` rule to all my pages so at least pre/code/textarea align as needed at least in FF and Chrome. cant do much for github's display or view-source on others' machines :(

**Comment by lawrence-dol** [comment] 2016-04-07 03:46
> how tab=8 spaces got standardized by w3c or watwg

Right?! But then I would say the same about back-dented closing braces, so what do I know. :-D

> the content-box default box model

That was done by an academic pencil-head in a dusty back room who'd never written a UI in his life. IMNSHO.

To be clear, it's only the source-view (CTL-U) that was wonky and the above setting fixes it. Other browsers may also be wonky. It's not the code formatting anywhere on GitHub or elsewhere, just the browser's view-source option. I just happen to use that to conveniently look at the source for the demos.

I've never had a problem with using space indenting, not once, in some 29 years (I don't count the years of BASIC and ASM; they had no indenting at all). The reason I've always eschewed tab-indenting is because they can't play well with others unless used religiously and only for indenting, not for alignment. Whereas spaces are always WYSIWYG.

**Closed** 2017-02-11 21:27 UTC
Labels: question
