### ISSUE TITLE
Bug with old element recycling (V1)

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#110] opened 2017-01-05 04:02 UTC
I found this problem with V1, and I'm reporting it in case it remains relevant for V2. 

The problem is that the old-body recycling seems to presume the body is not null, when it sometimes is. The fault is in this code:

    function findDonor(node, newParent, oldParent, fromIdx, toIdx) {
        var newIsView = u.isArr(node);
        var newKey = newIsView ? getViewKey(node[1], node[2]) : node.key;
        var oldKeys = oldParent.hasKeys;
        var newKeys = newParent.hasKeys;
        var oldBody = oldParent.body;
        var newBody = newParent.body;

        // fast exact match by key
        if (newKey !== null && oldKeys) {
            var idx = u.keyedIdx(newKey, oldBody, newIsView ? node[0] : null, fromIdx, toIdx);
            if (idx > -1)
                return [idx, DONOR_NODE];
            return null;
        }

        // if from or to > newbody length, return null
        // todo: from keys here
        fromIdx = fromIdx || 0;
        if (fromIdx > oldBody.length - 1) return null; 
        // ^^^ repeatedly and consistently get oldBody is null or oldBody.length is null here
        toIdx = toIdx === 0 ? 0 : toIdx || oldBody.length - 1;
    ...

To resolve it, I simply changed the marked line to:

        if (!oldBody || fromIdx > oldBody.length - 1) return null; 

Unexpected is that the error varies between `oldBody` and `oldBody.length`.

Note that to produce a replication would require considerable time and effort since the displays are complex and would need to be (tediously) whittled down to the simplest form that reproduces the error. I don't know if it's worth investing the effort to do that, yet.

**Comment by leeoniya** [comment] 2017-01-05 04:15
this function is significantly simpler in v2 [1], so chances are this doesnt apply. if all v1 tests still pass with your fix i can apply it without too much concern. ideally i'd add a regression test but i also dont have much motivation to hunt this to maintain the deprecated v1 :/

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/patch.js

**Comment by leeoniya** [comment] 2017-01-06 19:31
@lawrence-dol btw, is any porting to v2 on your horizon?

**Comment by lawrence-dol** [comment] 2017-01-06 19:51
@leeoniya

> is any porting to v2 on your horizon?

Yes, very much so. But I have to deliver the initial release over for QA first. So far the only complication that may take a little time to work through is my post-generation augmentation of the primary view based on host data which incorporates addressing into and searching the display grid. The rest I expect to be basic grunt work.

I expect to get to V2 before the end of this month.

**Comment by leeoniya** [comment] 2017-02-11 21:29
closing this, since this will likely stay open forever otherwise.

**Closed by leeoniya** 2017-02-11 21:29 UTC
Labels: needs testcase

**Comment by lawrence-dol** [comment] 2017-02-24 21:03
> is any porting to v2 on your horizon?

@leeoniya : I am finally proceeding with an effort to port to V2. If you have any docs available that discuss the differences or needed changes, I'm all ears.

**Comment by leeoniya** [comment] 2017-02-24 21:12
most of the stuff should be pretty low impact, ping me if you run into anything unexpected.

**Comment by lawrence-dol** [comment] 2017-02-24 21:21
@leeoniya : Thanks. I am thinking to open an issue entitled "Porting V1 to V2" and to record everything I do there. What do you think?

**Comment by leeoniya** [comment] 2017-02-24 21:22
sure, go for it
