### ISSUE TITLE
Duplicate node value `_class` and `attrs.class`?

### ISSUE THREAD

**Issue by lawrence-dol** [leeoniya/domvm#122] opened 2017-03-21 22:20 UTC
The class list is duplicated in every node, as `_class` and `attrs.class`. Is this intentional? If so, should we use `attrs.class` when searching nodes for a match, since the use of a leading underscore implies "internal; don't touch this"?

**Comment by leeoniya** [comment] 2017-03-21 22:36
`_class` is a static class defined as part of the tag in the template: `el(".foo.bar")`. this is additive with any class defined in the template's attrs: `{class: "baz"}`. during the preProc the static class gets merged into the attrs.class and represents the final class string that gets diff'd and assigned: `{class: "foo bar baz"}`.

there is a reason for this, and it's there for the following use-case:

```js
var vnode = el(".my-elem", "Hi!");
vnode.patch({class: "hidden"});
```

this allows you to retain any statically assigned class while being able to set *and unset* temporary or transient additional classes without having to know the full class-string externally, which comes in handy for css transitions. the duplication is expected behavior if you're using css-selector classes in your templates.

> when searching nodes for a match

the className is not used at all for matching up vnodes internally.

**Comment by lawrence-dol** [comment] 2017-03-22 00:13
This matters, in terms of what I can expect and rely upon.

So, given `elm("div.one.two.three")`, why am I seeing `attrs.class` = `one two three` before the view vtree has been returned to DOMVM? It looks like `domvm.createElement` is doing it. So is that correct and can I then depend on `attrs.class` being set by element creation as opposed to view processing?

Also, should not `_class` be just `class`, being the node's class list and not an "internal" property, per se (you mention the designed intent to access it such as for transitions).

**Comment by lawrence-dol** [comment] 2017-03-22 01:12
Also, in order to augment the class after building the node, but before returning the view, do I need to append to both `node._class` and `node.attrs.class`?

**Comment by leeoniya** [comment] 2017-03-22 01:53
you're right. it happens during vnode creation, this won't change.

_class is "private" because it's an impl detail and only exists to support vnode.patch which must be aware of what classes were defined statically to be able to augment them. the final composed class string will always live in attrs.class and you can modify that as needed. _class should not be used.

**Comment by lawrence-dol** [comment] 2017-03-22 02:11
Thanks. That's what I needed to know.

**Closed** 2017-03-22 02:30 UTC
